// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Kguie/portfolio-system/services/api/ent/lead"
	"github.com/Kguie/portfolio-system/services/api/ent/predicate"
)

// LeadUpdate is the builder for updating Lead entities.
type LeadUpdate struct {
	config
	hooks    []Hook
	mutation *LeadMutation
}

// Where appends a list predicates to the LeadUpdate builder.
func (lu *LeadUpdate) Where(ps ...predicate.Lead) *LeadUpdate {
	lu.mutation.Where(ps...)
	return lu
}

// SetName sets the "name" field.
func (lu *LeadUpdate) SetName(s string) *LeadUpdate {
	lu.mutation.SetName(s)
	return lu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (lu *LeadUpdate) SetNillableName(s *string) *LeadUpdate {
	if s != nil {
		lu.SetName(*s)
	}
	return lu
}

// SetEmail sets the "email" field.
func (lu *LeadUpdate) SetEmail(s string) *LeadUpdate {
	lu.mutation.SetEmail(s)
	return lu
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (lu *LeadUpdate) SetNillableEmail(s *string) *LeadUpdate {
	if s != nil {
		lu.SetEmail(*s)
	}
	return lu
}

// SetMessage sets the "message" field.
func (lu *LeadUpdate) SetMessage(s string) *LeadUpdate {
	lu.mutation.SetMessage(s)
	return lu
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (lu *LeadUpdate) SetNillableMessage(s *string) *LeadUpdate {
	if s != nil {
		lu.SetMessage(*s)
	}
	return lu
}

// SetIP sets the "ip" field.
func (lu *LeadUpdate) SetIP(s string) *LeadUpdate {
	lu.mutation.SetIP(s)
	return lu
}

// SetNillableIP sets the "ip" field if the given value is not nil.
func (lu *LeadUpdate) SetNillableIP(s *string) *LeadUpdate {
	if s != nil {
		lu.SetIP(*s)
	}
	return lu
}

// SetUserAgent sets the "user_agent" field.
func (lu *LeadUpdate) SetUserAgent(s string) *LeadUpdate {
	lu.mutation.SetUserAgent(s)
	return lu
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (lu *LeadUpdate) SetNillableUserAgent(s *string) *LeadUpdate {
	if s != nil {
		lu.SetUserAgent(*s)
	}
	return lu
}

// ClearUserAgent clears the value of the "user_agent" field.
func (lu *LeadUpdate) ClearUserAgent() *LeadUpdate {
	lu.mutation.ClearUserAgent()
	return lu
}

// Mutation returns the LeadMutation object of the builder.
func (lu *LeadUpdate) Mutation() *LeadMutation {
	return lu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (lu *LeadUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, lu.sqlSave, lu.mutation, lu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (lu *LeadUpdate) SaveX(ctx context.Context) int {
	affected, err := lu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (lu *LeadUpdate) Exec(ctx context.Context) error {
	_, err := lu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (lu *LeadUpdate) ExecX(ctx context.Context) {
	if err := lu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (lu *LeadUpdate) check() error {
	if v, ok := lu.mutation.Name(); ok {
		if err := lead.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Lead.name": %w`, err)}
		}
	}
	if v, ok := lu.mutation.Email(); ok {
		if err := lead.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "Lead.email": %w`, err)}
		}
	}
	if v, ok := lu.mutation.Message(); ok {
		if err := lead.MessageValidator(v); err != nil {
			return &ValidationError{Name: "message", err: fmt.Errorf(`ent: validator failed for field "Lead.message": %w`, err)}
		}
	}
	if v, ok := lu.mutation.IP(); ok {
		if err := lead.IPValidator(v); err != nil {
			return &ValidationError{Name: "ip", err: fmt.Errorf(`ent: validator failed for field "Lead.ip": %w`, err)}
		}
	}
	return nil
}

func (lu *LeadUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := lu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(lead.Table, lead.Columns, sqlgraph.NewFieldSpec(lead.FieldID, field.TypeString))
	if ps := lu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := lu.mutation.Name(); ok {
		_spec.SetField(lead.FieldName, field.TypeString, value)
	}
	if value, ok := lu.mutation.Email(); ok {
		_spec.SetField(lead.FieldEmail, field.TypeString, value)
	}
	if value, ok := lu.mutation.Message(); ok {
		_spec.SetField(lead.FieldMessage, field.TypeString, value)
	}
	if value, ok := lu.mutation.IP(); ok {
		_spec.SetField(lead.FieldIP, field.TypeString, value)
	}
	if value, ok := lu.mutation.UserAgent(); ok {
		_spec.SetField(lead.FieldUserAgent, field.TypeString, value)
	}
	if lu.mutation.UserAgentCleared() {
		_spec.ClearField(lead.FieldUserAgent, field.TypeString)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, lu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{lead.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	lu.mutation.done = true
	return n, nil
}

// LeadUpdateOne is the builder for updating a single Lead entity.
type LeadUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LeadMutation
}

// SetName sets the "name" field.
func (luo *LeadUpdateOne) SetName(s string) *LeadUpdateOne {
	luo.mutation.SetName(s)
	return luo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (luo *LeadUpdateOne) SetNillableName(s *string) *LeadUpdateOne {
	if s != nil {
		luo.SetName(*s)
	}
	return luo
}

// SetEmail sets the "email" field.
func (luo *LeadUpdateOne) SetEmail(s string) *LeadUpdateOne {
	luo.mutation.SetEmail(s)
	return luo
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (luo *LeadUpdateOne) SetNillableEmail(s *string) *LeadUpdateOne {
	if s != nil {
		luo.SetEmail(*s)
	}
	return luo
}

// SetMessage sets the "message" field.
func (luo *LeadUpdateOne) SetMessage(s string) *LeadUpdateOne {
	luo.mutation.SetMessage(s)
	return luo
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (luo *LeadUpdateOne) SetNillableMessage(s *string) *LeadUpdateOne {
	if s != nil {
		luo.SetMessage(*s)
	}
	return luo
}

// SetIP sets the "ip" field.
func (luo *LeadUpdateOne) SetIP(s string) *LeadUpdateOne {
	luo.mutation.SetIP(s)
	return luo
}

// SetNillableIP sets the "ip" field if the given value is not nil.
func (luo *LeadUpdateOne) SetNillableIP(s *string) *LeadUpdateOne {
	if s != nil {
		luo.SetIP(*s)
	}
	return luo
}

// SetUserAgent sets the "user_agent" field.
func (luo *LeadUpdateOne) SetUserAgent(s string) *LeadUpdateOne {
	luo.mutation.SetUserAgent(s)
	return luo
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (luo *LeadUpdateOne) SetNillableUserAgent(s *string) *LeadUpdateOne {
	if s != nil {
		luo.SetUserAgent(*s)
	}
	return luo
}

// ClearUserAgent clears the value of the "user_agent" field.
func (luo *LeadUpdateOne) ClearUserAgent() *LeadUpdateOne {
	luo.mutation.ClearUserAgent()
	return luo
}

// Mutation returns the LeadMutation object of the builder.
func (luo *LeadUpdateOne) Mutation() *LeadMutation {
	return luo.mutation
}

// Where appends a list predicates to the LeadUpdate builder.
func (luo *LeadUpdateOne) Where(ps ...predicate.Lead) *LeadUpdateOne {
	luo.mutation.Where(ps...)
	return luo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (luo *LeadUpdateOne) Select(field string, fields ...string) *LeadUpdateOne {
	luo.fields = append([]string{field}, fields...)
	return luo
}

// Save executes the query and returns the updated Lead entity.
func (luo *LeadUpdateOne) Save(ctx context.Context) (*Lead, error) {
	return withHooks(ctx, luo.sqlSave, luo.mutation, luo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (luo *LeadUpdateOne) SaveX(ctx context.Context) *Lead {
	node, err := luo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (luo *LeadUpdateOne) Exec(ctx context.Context) error {
	_, err := luo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (luo *LeadUpdateOne) ExecX(ctx context.Context) {
	if err := luo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (luo *LeadUpdateOne) check() error {
	if v, ok := luo.mutation.Name(); ok {
		if err := lead.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Lead.name": %w`, err)}
		}
	}
	if v, ok := luo.mutation.Email(); ok {
		if err := lead.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "Lead.email": %w`, err)}
		}
	}
	if v, ok := luo.mutation.Message(); ok {
		if err := lead.MessageValidator(v); err != nil {
			return &ValidationError{Name: "message", err: fmt.Errorf(`ent: validator failed for field "Lead.message": %w`, err)}
		}
	}
	if v, ok := luo.mutation.IP(); ok {
		if err := lead.IPValidator(v); err != nil {
			return &ValidationError{Name: "ip", err: fmt.Errorf(`ent: validator failed for field "Lead.ip": %w`, err)}
		}
	}
	return nil
}

func (luo *LeadUpdateOne) sqlSave(ctx context.Context) (_node *Lead, err error) {
	if err := luo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(lead.Table, lead.Columns, sqlgraph.NewFieldSpec(lead.FieldID, field.TypeString))
	id, ok := luo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Lead.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := luo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, lead.FieldID)
		for _, f := range fields {
			if !lead.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != lead.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := luo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := luo.mutation.Name(); ok {
		_spec.SetField(lead.FieldName, field.TypeString, value)
	}
	if value, ok := luo.mutation.Email(); ok {
		_spec.SetField(lead.FieldEmail, field.TypeString, value)
	}
	if value, ok := luo.mutation.Message(); ok {
		_spec.SetField(lead.FieldMessage, field.TypeString, value)
	}
	if value, ok := luo.mutation.IP(); ok {
		_spec.SetField(lead.FieldIP, field.TypeString, value)
	}
	if value, ok := luo.mutation.UserAgent(); ok {
		_spec.SetField(lead.FieldUserAgent, field.TypeString, value)
	}
	if luo.mutation.UserAgentCleared() {
		_spec.ClearField(lead.FieldUserAgent, field.TypeString)
	}
	_node = &Lead{config: luo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, luo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{lead.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	luo.mutation.done = true
	return _node, nil
}
