// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Kguie/portfolio-system/services/api/ent/lead"
)

// LeadCreate is the builder for creating a Lead entity.
type LeadCreate struct {
	config
	mutation *LeadMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (lc *LeadCreate) SetName(s string) *LeadCreate {
	lc.mutation.SetName(s)
	return lc
}

// SetEmail sets the "email" field.
func (lc *LeadCreate) SetEmail(s string) *LeadCreate {
	lc.mutation.SetEmail(s)
	return lc
}

// SetMessage sets the "message" field.
func (lc *LeadCreate) SetMessage(s string) *LeadCreate {
	lc.mutation.SetMessage(s)
	return lc
}

// SetIP sets the "ip" field.
func (lc *LeadCreate) SetIP(s string) *LeadCreate {
	lc.mutation.SetIP(s)
	return lc
}

// SetUserAgent sets the "user_agent" field.
func (lc *LeadCreate) SetUserAgent(s string) *LeadCreate {
	lc.mutation.SetUserAgent(s)
	return lc
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (lc *LeadCreate) SetNillableUserAgent(s *string) *LeadCreate {
	if s != nil {
		lc.SetUserAgent(*s)
	}
	return lc
}

// SetCreatedAt sets the "created_at" field.
func (lc *LeadCreate) SetCreatedAt(t time.Time) *LeadCreate {
	lc.mutation.SetCreatedAt(t)
	return lc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (lc *LeadCreate) SetNillableCreatedAt(t *time.Time) *LeadCreate {
	if t != nil {
		lc.SetCreatedAt(*t)
	}
	return lc
}

// SetID sets the "id" field.
func (lc *LeadCreate) SetID(s string) *LeadCreate {
	lc.mutation.SetID(s)
	return lc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (lc *LeadCreate) SetNillableID(s *string) *LeadCreate {
	if s != nil {
		lc.SetID(*s)
	}
	return lc
}

// Mutation returns the LeadMutation object of the builder.
func (lc *LeadCreate) Mutation() *LeadMutation {
	return lc.mutation
}

// Save creates the Lead in the database.
func (lc *LeadCreate) Save(ctx context.Context) (*Lead, error) {
	lc.defaults()
	return withHooks(ctx, lc.sqlSave, lc.mutation, lc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (lc *LeadCreate) SaveX(ctx context.Context) *Lead {
	v, err := lc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (lc *LeadCreate) Exec(ctx context.Context) error {
	_, err := lc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (lc *LeadCreate) ExecX(ctx context.Context) {
	if err := lc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (lc *LeadCreate) defaults() {
	if _, ok := lc.mutation.CreatedAt(); !ok {
		v := lead.DefaultCreatedAt()
		lc.mutation.SetCreatedAt(v)
	}
	if _, ok := lc.mutation.ID(); !ok {
		v := lead.DefaultID()
		lc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (lc *LeadCreate) check() error {
	if _, ok := lc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Lead.name"`)}
	}
	if v, ok := lc.mutation.Name(); ok {
		if err := lead.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Lead.name": %w`, err)}
		}
	}
	if _, ok := lc.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`ent: missing required field "Lead.email"`)}
	}
	if v, ok := lc.mutation.Email(); ok {
		if err := lead.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "Lead.email": %w`, err)}
		}
	}
	if _, ok := lc.mutation.Message(); !ok {
		return &ValidationError{Name: "message", err: errors.New(`ent: missing required field "Lead.message"`)}
	}
	if v, ok := lc.mutation.Message(); ok {
		if err := lead.MessageValidator(v); err != nil {
			return &ValidationError{Name: "message", err: fmt.Errorf(`ent: validator failed for field "Lead.message": %w`, err)}
		}
	}
	if _, ok := lc.mutation.IP(); !ok {
		return &ValidationError{Name: "ip", err: errors.New(`ent: missing required field "Lead.ip"`)}
	}
	if v, ok := lc.mutation.IP(); ok {
		if err := lead.IPValidator(v); err != nil {
			return &ValidationError{Name: "ip", err: fmt.Errorf(`ent: validator failed for field "Lead.ip": %w`, err)}
		}
	}
	if _, ok := lc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Lead.created_at"`)}
	}
	return nil
}

func (lc *LeadCreate) sqlSave(ctx context.Context) (*Lead, error) {
	if err := lc.check(); err != nil {
		return nil, err
	}
	_node, _spec := lc.createSpec()
	if err := sqlgraph.CreateNode(ctx, lc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Lead.ID type: %T", _spec.ID.Value)
		}
	}
	lc.mutation.id = &_node.ID
	lc.mutation.done = true
	return _node, nil
}

func (lc *LeadCreate) createSpec() (*Lead, *sqlgraph.CreateSpec) {
	var (
		_node = &Lead{config: lc.config}
		_spec = sqlgraph.NewCreateSpec(lead.Table, sqlgraph.NewFieldSpec(lead.FieldID, field.TypeString))
	)
	if id, ok := lc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := lc.mutation.Name(); ok {
		_spec.SetField(lead.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := lc.mutation.Email(); ok {
		_spec.SetField(lead.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := lc.mutation.Message(); ok {
		_spec.SetField(lead.FieldMessage, field.TypeString, value)
		_node.Message = value
	}
	if value, ok := lc.mutation.IP(); ok {
		_spec.SetField(lead.FieldIP, field.TypeString, value)
		_node.IP = value
	}
	if value, ok := lc.mutation.UserAgent(); ok {
		_spec.SetField(lead.FieldUserAgent, field.TypeString, value)
		_node.UserAgent = &value
	}
	if value, ok := lc.mutation.CreatedAt(); ok {
		_spec.SetField(lead.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// LeadCreateBulk is the builder for creating many Lead entities in bulk.
type LeadCreateBulk struct {
	config
	err      error
	builders []*LeadCreate
}

// Save creates the Lead entities in the database.
func (lcb *LeadCreateBulk) Save(ctx context.Context) ([]*Lead, error) {
	if lcb.err != nil {
		return nil, lcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(lcb.builders))
	nodes := make([]*Lead, len(lcb.builders))
	mutators := make([]Mutator, len(lcb.builders))
	for i := range lcb.builders {
		func(i int, root context.Context) {
			builder := lcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LeadMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, lcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, lcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, lcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (lcb *LeadCreateBulk) SaveX(ctx context.Context) []*Lead {
	v, err := lcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (lcb *LeadCreateBulk) Exec(ctx context.Context) error {
	_, err := lcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (lcb *LeadCreateBulk) ExecX(ctx context.Context) {
	if err := lcb.Exec(ctx); err != nil {
		panic(err)
	}
}
