// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Kguie/portfolio-system/services/api/ent/predicate"
	"github.com/Kguie/portfolio-system/services/api/ent/project"
	"github.com/Kguie/portfolio-system/services/api/ent/schema"
)

// ProjectUpdate is the builder for updating Project entities.
type ProjectUpdate struct {
	config
	hooks    []Hook
	mutation *ProjectMutation
}

// Where appends a list predicates to the ProjectUpdate builder.
func (pu *ProjectUpdate) Where(ps ...predicate.Project) *ProjectUpdate {
	pu.mutation.Where(ps...)
	return pu
}

// SetSlug sets the "slug" field.
func (pu *ProjectUpdate) SetSlug(s string) *ProjectUpdate {
	pu.mutation.SetSlug(s)
	return pu
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (pu *ProjectUpdate) SetNillableSlug(s *string) *ProjectUpdate {
	if s != nil {
		pu.SetSlug(*s)
	}
	return pu
}

// SetTitle sets the "title" field.
func (pu *ProjectUpdate) SetTitle(s string) *ProjectUpdate {
	pu.mutation.SetTitle(s)
	return pu
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (pu *ProjectUpdate) SetNillableTitle(s *string) *ProjectUpdate {
	if s != nil {
		pu.SetTitle(*s)
	}
	return pu
}

// SetSummary sets the "summary" field.
func (pu *ProjectUpdate) SetSummary(s string) *ProjectUpdate {
	pu.mutation.SetSummary(s)
	return pu
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (pu *ProjectUpdate) SetNillableSummary(s *string) *ProjectUpdate {
	if s != nil {
		pu.SetSummary(*s)
	}
	return pu
}

// SetTags sets the "tags" field.
func (pu *ProjectUpdate) SetTags(s []string) *ProjectUpdate {
	pu.mutation.SetTags(s)
	return pu
}

// AppendTags appends s to the "tags" field.
func (pu *ProjectUpdate) AppendTags(s []string) *ProjectUpdate {
	pu.mutation.AppendTags(s)
	return pu
}

// SetLinks sets the "links" field.
func (pu *ProjectUpdate) SetLinks(sl schema.ProjectLinks) *ProjectUpdate {
	pu.mutation.SetLinks(sl)
	return pu
}

// SetNillableLinks sets the "links" field if the given value is not nil.
func (pu *ProjectUpdate) SetNillableLinks(sl *schema.ProjectLinks) *ProjectUpdate {
	if sl != nil {
		pu.SetLinks(*sl)
	}
	return pu
}

// SetFeatured sets the "featured" field.
func (pu *ProjectUpdate) SetFeatured(b bool) *ProjectUpdate {
	pu.mutation.SetFeatured(b)
	return pu
}

// SetNillableFeatured sets the "featured" field if the given value is not nil.
func (pu *ProjectUpdate) SetNillableFeatured(b *bool) *ProjectUpdate {
	if b != nil {
		pu.SetFeatured(*b)
	}
	return pu
}

// SetUpdatedAt sets the "updated_at" field.
func (pu *ProjectUpdate) SetUpdatedAt(t time.Time) *ProjectUpdate {
	pu.mutation.SetUpdatedAt(t)
	return pu
}

// Mutation returns the ProjectMutation object of the builder.
func (pu *ProjectUpdate) Mutation() *ProjectMutation {
	return pu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (pu *ProjectUpdate) Save(ctx context.Context) (int, error) {
	pu.defaults()
	return withHooks(ctx, pu.sqlSave, pu.mutation, pu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (pu *ProjectUpdate) SaveX(ctx context.Context) int {
	affected, err := pu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (pu *ProjectUpdate) Exec(ctx context.Context) error {
	_, err := pu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pu *ProjectUpdate) ExecX(ctx context.Context) {
	if err := pu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (pu *ProjectUpdate) defaults() {
	if _, ok := pu.mutation.UpdatedAt(); !ok {
		v := project.UpdateDefaultUpdatedAt()
		pu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pu *ProjectUpdate) check() error {
	if v, ok := pu.mutation.Slug(); ok {
		if err := project.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "Project.slug": %w`, err)}
		}
	}
	if v, ok := pu.mutation.Title(); ok {
		if err := project.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Project.title": %w`, err)}
		}
	}
	if v, ok := pu.mutation.Summary(); ok {
		if err := project.SummaryValidator(v); err != nil {
			return &ValidationError{Name: "summary", err: fmt.Errorf(`ent: validator failed for field "Project.summary": %w`, err)}
		}
	}
	return nil
}

func (pu *ProjectUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := pu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(project.Table, project.Columns, sqlgraph.NewFieldSpec(project.FieldID, field.TypeString))
	if ps := pu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pu.mutation.Slug(); ok {
		_spec.SetField(project.FieldSlug, field.TypeString, value)
	}
	if value, ok := pu.mutation.Title(); ok {
		_spec.SetField(project.FieldTitle, field.TypeString, value)
	}
	if value, ok := pu.mutation.Summary(); ok {
		_spec.SetField(project.FieldSummary, field.TypeString, value)
	}
	if value, ok := pu.mutation.Tags(); ok {
		_spec.SetField(project.FieldTags, field.TypeJSON, value)
	}
	if value, ok := pu.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, project.FieldTags, value)
		})
	}
	if value, ok := pu.mutation.Links(); ok {
		_spec.SetField(project.FieldLinks, field.TypeJSON, value)
	}
	if value, ok := pu.mutation.Featured(); ok {
		_spec.SetField(project.FieldFeatured, field.TypeBool, value)
	}
	if value, ok := pu.mutation.UpdatedAt(); ok {
		_spec.SetField(project.FieldUpdatedAt, field.TypeTime, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, pu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{project.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	pu.mutation.done = true
	return n, nil
}

// ProjectUpdateOne is the builder for updating a single Project entity.
type ProjectUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProjectMutation
}

// SetSlug sets the "slug" field.
func (puo *ProjectUpdateOne) SetSlug(s string) *ProjectUpdateOne {
	puo.mutation.SetSlug(s)
	return puo
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (puo *ProjectUpdateOne) SetNillableSlug(s *string) *ProjectUpdateOne {
	if s != nil {
		puo.SetSlug(*s)
	}
	return puo
}

// SetTitle sets the "title" field.
func (puo *ProjectUpdateOne) SetTitle(s string) *ProjectUpdateOne {
	puo.mutation.SetTitle(s)
	return puo
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (puo *ProjectUpdateOne) SetNillableTitle(s *string) *ProjectUpdateOne {
	if s != nil {
		puo.SetTitle(*s)
	}
	return puo
}

// SetSummary sets the "summary" field.
func (puo *ProjectUpdateOne) SetSummary(s string) *ProjectUpdateOne {
	puo.mutation.SetSummary(s)
	return puo
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (puo *ProjectUpdateOne) SetNillableSummary(s *string) *ProjectUpdateOne {
	if s != nil {
		puo.SetSummary(*s)
	}
	return puo
}

// SetTags sets the "tags" field.
func (puo *ProjectUpdateOne) SetTags(s []string) *ProjectUpdateOne {
	puo.mutation.SetTags(s)
	return puo
}

// AppendTags appends s to the "tags" field.
func (puo *ProjectUpdateOne) AppendTags(s []string) *ProjectUpdateOne {
	puo.mutation.AppendTags(s)
	return puo
}

// SetLinks sets the "links" field.
func (puo *ProjectUpdateOne) SetLinks(sl schema.ProjectLinks) *ProjectUpdateOne {
	puo.mutation.SetLinks(sl)
	return puo
}

// SetNillableLinks sets the "links" field if the given value is not nil.
func (puo *ProjectUpdateOne) SetNillableLinks(sl *schema.ProjectLinks) *ProjectUpdateOne {
	if sl != nil {
		puo.SetLinks(*sl)
	}
	return puo
}

// SetFeatured sets the "featured" field.
func (puo *ProjectUpdateOne) SetFeatured(b bool) *ProjectUpdateOne {
	puo.mutation.SetFeatured(b)
	return puo
}

// SetNillableFeatured sets the "featured" field if the given value is not nil.
func (puo *ProjectUpdateOne) SetNillableFeatured(b *bool) *ProjectUpdateOne {
	if b != nil {
		puo.SetFeatured(*b)
	}
	return puo
}

// SetUpdatedAt sets the "updated_at" field.
func (puo *ProjectUpdateOne) SetUpdatedAt(t time.Time) *ProjectUpdateOne {
	puo.mutation.SetUpdatedAt(t)
	return puo
}

// Mutation returns the ProjectMutation object of the builder.
func (puo *ProjectUpdateOne) Mutation() *ProjectMutation {
	return puo.mutation
}

// Where appends a list predicates to the ProjectUpdate builder.
func (puo *ProjectUpdateOne) Where(ps ...predicate.Project) *ProjectUpdateOne {
	puo.mutation.Where(ps...)
	return puo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (puo *ProjectUpdateOne) Select(field string, fields ...string) *ProjectUpdateOne {
	puo.fields = append([]string{field}, fields...)
	return puo
}

// Save executes the query and returns the updated Project entity.
func (puo *ProjectUpdateOne) Save(ctx context.Context) (*Project, error) {
	puo.defaults()
	return withHooks(ctx, puo.sqlSave, puo.mutation, puo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (puo *ProjectUpdateOne) SaveX(ctx context.Context) *Project {
	node, err := puo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (puo *ProjectUpdateOne) Exec(ctx context.Context) error {
	_, err := puo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (puo *ProjectUpdateOne) ExecX(ctx context.Context) {
	if err := puo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (puo *ProjectUpdateOne) defaults() {
	if _, ok := puo.mutation.UpdatedAt(); !ok {
		v := project.UpdateDefaultUpdatedAt()
		puo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (puo *ProjectUpdateOne) check() error {
	if v, ok := puo.mutation.Slug(); ok {
		if err := project.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "Project.slug": %w`, err)}
		}
	}
	if v, ok := puo.mutation.Title(); ok {
		if err := project.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Project.title": %w`, err)}
		}
	}
	if v, ok := puo.mutation.Summary(); ok {
		if err := project.SummaryValidator(v); err != nil {
			return &ValidationError{Name: "summary", err: fmt.Errorf(`ent: validator failed for field "Project.summary": %w`, err)}
		}
	}
	return nil
}

func (puo *ProjectUpdateOne) sqlSave(ctx context.Context) (_node *Project, err error) {
	if err := puo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(project.Table, project.Columns, sqlgraph.NewFieldSpec(project.FieldID, field.TypeString))
	id, ok := puo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Project.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := puo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, project.FieldID)
		for _, f := range fields {
			if !project.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != project.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := puo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := puo.mutation.Slug(); ok {
		_spec.SetField(project.FieldSlug, field.TypeString, value)
	}
	if value, ok := puo.mutation.Title(); ok {
		_spec.SetField(project.FieldTitle, field.TypeString, value)
	}
	if value, ok := puo.mutation.Summary(); ok {
		_spec.SetField(project.FieldSummary, field.TypeString, value)
	}
	if value, ok := puo.mutation.Tags(); ok {
		_spec.SetField(project.FieldTags, field.TypeJSON, value)
	}
	if value, ok := puo.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, project.FieldTags, value)
		})
	}
	if value, ok := puo.mutation.Links(); ok {
		_spec.SetField(project.FieldLinks, field.TypeJSON, value)
	}
	if value, ok := puo.mutation.Featured(); ok {
		_spec.SetField(project.FieldFeatured, field.TypeBool, value)
	}
	if value, ok := puo.mutation.UpdatedAt(); ok {
		_spec.SetField(project.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Project{config: puo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, puo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{project.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	puo.mutation.done = true
	return _node, nil
}
