// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/Kguie/portfolio-system/services/api/ent/lead"
	"github.com/Kguie/portfolio-system/services/api/ent/project"
	"github.com/Kguie/portfolio-system/services/api/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	leadFields := schema.Lead{}.Fields()
	_ = leadFields
	// leadDescName is the schema descriptor for name field.
	leadDescName := leadFields[1].Descriptor()
	// lead.NameValidator is a validator for the "name" field. It is called by the builders before save.
	lead.NameValidator = leadDescName.Validators[0].(func(string) error)
	// leadDescEmail is the schema descriptor for email field.
	leadDescEmail := leadFields[2].Descriptor()
	// lead.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	lead.EmailValidator = leadDescEmail.Validators[0].(func(string) error)
	// leadDescMessage is the schema descriptor for message field.
	leadDescMessage := leadFields[3].Descriptor()
	// lead.MessageValidator is a validator for the "message" field. It is called by the builders before save.
	lead.MessageValidator = leadDescMessage.Validators[0].(func(string) error)
	// leadDescIP is the schema descriptor for ip field.
	leadDescIP := leadFields[4].Descriptor()
	// lead.IPValidator is a validator for the "ip" field. It is called by the builders before save.
	lead.IPValidator = leadDescIP.Validators[0].(func(string) error)
	// leadDescCreatedAt is the schema descriptor for created_at field.
	leadDescCreatedAt := leadFields[6].Descriptor()
	// lead.DefaultCreatedAt holds the default value on creation for the created_at field.
	lead.DefaultCreatedAt = leadDescCreatedAt.Default.(func() time.Time)
	// leadDescID is the schema descriptor for id field.
	leadDescID := leadFields[0].Descriptor()
	// lead.DefaultID holds the default value on creation for the id field.
	lead.DefaultID = leadDescID.Default.(func() string)
	projectFields := schema.Project{}.Fields()
	_ = projectFields
	// projectDescSlug is the schema descriptor for slug field.
	projectDescSlug := projectFields[1].Descriptor()
	// project.SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	project.SlugValidator = projectDescSlug.Validators[0].(func(string) error)
	// projectDescTitle is the schema descriptor for title field.
	projectDescTitle := projectFields[2].Descriptor()
	// project.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	project.TitleValidator = projectDescTitle.Validators[0].(func(string) error)
	// projectDescSummary is the schema descriptor for summary field.
	projectDescSummary := projectFields[3].Descriptor()
	// project.SummaryValidator is a validator for the "summary" field. It is called by the builders before save.
	project.SummaryValidator = projectDescSummary.Validators[0].(func(string) error)
	// projectDescTags is the schema descriptor for tags field.
	projectDescTags := projectFields[4].Descriptor()
	// project.DefaultTags holds the default value on creation for the tags field.
	project.DefaultTags = projectDescTags.Default.([]string)
	// projectDescLinks is the schema descriptor for links field.
	projectDescLinks := projectFields[5].Descriptor()
	// project.DefaultLinks holds the default value on creation for the links field.
	project.DefaultLinks = projectDescLinks.Default.(schema.ProjectLinks)
	// projectDescFeatured is the schema descriptor for featured field.
	projectDescFeatured := projectFields[6].Descriptor()
	// project.DefaultFeatured holds the default value on creation for the featured field.
	project.DefaultFeatured = projectDescFeatured.Default.(bool)
	// projectDescCreatedAt is the schema descriptor for created_at field.
	projectDescCreatedAt := projectFields[7].Descriptor()
	// project.DefaultCreatedAt holds the default value on creation for the created_at field.
	project.DefaultCreatedAt = projectDescCreatedAt.Default.(func() time.Time)
	// projectDescUpdatedAt is the schema descriptor for updated_at field.
	projectDescUpdatedAt := projectFields[8].Descriptor()
	// project.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	project.DefaultUpdatedAt = projectDescUpdatedAt.Default.(func() time.Time)
	// project.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	project.UpdateDefaultUpdatedAt = projectDescUpdatedAt.UpdateDefault.(func() time.Time)
	// projectDescID is the schema descriptor for id field.
	projectDescID := projectFields[0].Descriptor()
	// project.DefaultID holds the default value on creation for the id field.
	project.DefaultID = projectDescID.Default.(func() string)
}
